version: "3.9"

services:
    db:
        image: postgres:15
        container_name: db
        restart: unless-stopped
        expose:
            - "5432"
        # Remove ports later
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: minime
