version: "3.9"

services:
    db:
        image: postgres:15
        container_name: mini_db
        restart: unless-stopped
        expose:
            - "5432"
        # Remove ports later
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: minime
        volumes:
            - postgres_dev:/var/lib/postgresql/data

    app:
        build:
            context: ../../
            dockerfile: devops/docker/Dockerfile-backend
        container_name: mini_app
        restart: always
        ports:
            - "8080:8080"
        command: ["runserver"]
        volumes:
            - ../../:/minime/
        depends_on:
            - db

volumes:
    postgres_dev:
