version: "3.9"

services:
    db:
        image: postgres:15
        container_name: mini_db
        restart: unless-stopped
        expose:
            - "5432"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: minime
        volumes:
            - postgres_dev:/var/lib/postgresql/data

    frontend:
        build:
            context: ../../
            dockerfile: devops/docker/Dockerfile-frontend
        container_name: mini_frontend
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ../../frontend/:/minime/

    backend:
        build:
            context: ../../
            dockerfile: devops/docker/Dockerfile-backend
        container_name: mini_backend
        restart: always
        ports:
            - "8080:8080"
        command: ["runserver"]
        environment:
            SPRING_APPLICATION_JSON: '{
                "spring.datasource.url": "jdbc:postgresql://db:5432/minime"
            }'
        volumes:
            - ../../:/minime/
        depends_on:
            - db
            - frontend

volumes:
    postgres_dev:
