name: tests
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['master']

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Oracle JDK 20
        uses: oracle-actions/setup-java@v1
        with:
          website: oracle.com
          release: 20

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
